version: '3.8'

services:
  # ============================================================
  # Application Services
  # ============================================================
  config-server:
    build: ./config-server
    container_name: config-server
    environment:
      SPRING_PROFILES_ACTIVE: native
    ports: ["8889:8889"]
    networks: [ecommerce-network]

  auth-service:
    build: ./auth-service
    container_name: auth-service
    environment: {SPRING_PROFILES_ACTIVE: local, CONFIG_SERVER_HOST: config-server}
    depends_on: [config-server, auth-db]
    networks: [ecommerce-network]

  user-service:
    build: ./user-service
    container_name: user-service
    environment: {SPRING_PROFILES_ACTIVE: local, CONFIG_SERVER_HOST: config-server}
    depends_on: [config-server, user-db]
    networks: [ecommerce-network]

  catalog-service:
    build: ./catalog-service
    container_name: catalog-service
    environment: {SPRING_PROFILES_ACTIVE: local, CONFIG_SERVER_HOST: config-server, CATALOG_REPOSITORY_TYPE: mongo, CATALOG_CACHE_TYPE: redis}
    depends_on: [config-server, catalog-db, redis]
    networks: [ecommerce-network]

  inventory-service:
    build: ./inventory-service
    container_name: inventory-service
    environment: {SPRING_PROFILES_ACTIVE: local, CONFIG_SERVER_HOST: config-server, SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092}
    depends_on: [config-server, inventory-db, kafka]
    networks: [ecommerce-network]

  payment-service:
    build: ./payment-service
    container_name: payment-service
    environment: {SPRING_PROFILES_ACTIVE: local, CONFIG_SERVER_HOST: config-server, SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092}
    depends_on: [config-server, kafka]
    networks: [ecommerce-network]

  notification-service:
    build: ./notification-service
    container_name: notification-service
    environment: {SPRING_PROFILES_ACTIVE: local, CONFIG_SERVER_HOST: config-server, SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092}
    depends_on: [config-server, kafka]
    networks: [ecommerce-network]

  order-service:
    build: ./order-service
    container_name: order-service
    environment:
      SPRING_PROFILES_ACTIVE: local
      CONFIG_SERVER_HOST: config-server
      CATALOG_SERVICE_URL: http://catalog-service:8082
      INVENTORY_SERVICE_URL: http://inventory-service:8086
      PAYMENT_SERVICE_URL: http://payment-service:8088
      USER_SERVICE_URL: http://user-service:8087
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on: [config-server, order-db, catalog-service, inventory-service, payment-service, user-service, kafka]
    networks: [ecommerce-network]

  gateway-service:
    build: ./gateway-service
    container_name: gateway-service
    environment:
      SPRING_PROFILES_ACTIVE: local
      CONFIG_SERVER_HOST: config-server
      AUTH_SERVICE_URL: http://auth-service:8081
      USER_SERVICE_URL: http://user-service:8087
      CATALOG_SERVICE_URL: http://catalog-service:8082
      INVENTORY_SERVICE_URL: http://inventory-service:8086
      ORDER_SERVICE_URL: http://order-service:8083
      PAYMENT_SERVICE_URL: http://payment-service:8088
      NOTIFICATION_SERVICE_URL: http://notification-service:8084
      SPRING_REDIS_HOST: redis
    depends_on: [config-server, redis, auth-service, user-service, catalog-service, inventory-service, order-service, payment-service, notification-service]
    ports: ["8080:8080"]
    networks: [ecommerce-network]

  web-storefront:
    build: ./web-storefront
    container_name: web-storefront
    environment: {GATEWAY_URL: http://gateway-service:8080}
    depends_on: [gateway-service]
    ports: ["8090:8090"]
    networks: [ecommerce-network]



  # ============================================================
  # PostgreSQL - Auth Service
  # ============================================================
  auth-db:
    image: postgres:15.4-alpine
    container_name: auth-db
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - auth-db-data:/var/lib/postgresql/data
    networks:
      - ecommerce-network

  # ============================================================
  # PostgreSQL - Order Service
  # ============================================================
  order-db:
    image: postgres:15.4-alpine
    container_name: order-db
    environment:
      POSTGRES_DB: order_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - order-db-data:/var/lib/postgresql/data
    networks:
      - ecommerce-network

  # ============================================================
  # PostgreSQL - User Service
  # ============================================================
  user-db:
    image: postgres:15.4-alpine
    container_name: user-db
    environment:
      POSTGRES_DB: user_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    volumes:
      - user-db-data:/var/lib/postgresql/data
    networks:
      - ecommerce-network

  # ============================================================
  # PostgreSQL - Inventory Service
  # ============================================================
  inventory-db:
    image: postgres:15.4-alpine
    container_name: inventory-db
    environment:
      POSTGRES_DB: inventory_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5435:5432"
    volumes:
      - inventory-db-data:/var/lib/postgresql/data
    networks:
      - ecommerce-network

  # ============================================================
  # MongoDB - Catalog Service
  # ============================================================
  catalog-db:
    image: mongo:7.0
    container_name: catalog-db
    ports:
      - "27017:27017"
    volumes:
      - catalog-db-data:/data/db
    networks:
      - ecommerce-network

  # ============================================================
  # Redis - Cache / Rate Limiting
  # ============================================================
  redis:
    image: redis:7.2-alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - ecommerce-network

  # ============================================================
  # Zookeeper - Kafka Dependency
  # ============================================================
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - ecommerce-network

  # ============================================================
  # Kafka
  # ============================================================
  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9092,EXTERNAL://0.0.0.0:29092

      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL://localhost:29092

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT

      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

    networks:
      - ecommerce-network


  # ============================================================
  # Zipkin - Distributed Tracing
  # ============================================================
  zipkin:
    image: openzipkin/zipkin:3
    container_name: zipkin
    ports:
      - "9411:9411"
    networks:
      - ecommerce-network

  # ============================================================
  # Prometheus
  # ============================================================
  prometheus:
    image: prom/prometheus:v2.48.0
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    networks:
      - ecommerce-network

  # ============================================================
  # Grafana
  # ============================================================
  grafana:
    image: grafana/grafana:10.2.0
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - grafana-data:/var/lib/grafana
      - ./monitoring/grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./monitoring/grafana/datasources:/etc/grafana/provisioning/datasources
    depends_on:
      - prometheus
    networks:
      - ecommerce-network

# ================================================================
# Persistent Volumes
# ================================================================
volumes:
  auth-db-data:
  order-db-data:
  user-db-data:
  inventory-db-data:
  catalog-db-data:
  prometheus-data:
  grafana-data:

# ================================================================
# Docker Network
# ================================================================
networks:
  ecommerce-network:
    driver: bridge