global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'gateway-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['gateway-service:8080']
        labels:
          application: 'gateway-service'

  - job_name: 'auth-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['auth-service:8081']
        labels:
          application: 'auth-service'

  - job_name: 'catalog-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['catalog-service:8082']
        labels:
          application: 'catalog-service'

  - job_name: 'order-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'order-service:8083' ]
        labels:
          application: 'order-service'

  - job_name: 'notification-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'notification-service:8084' ]
        labels:
          application: 'notification-service'

  - job_name: 'inventory-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'inventory-service:8086' ]
        labels:
          application: 'inventory-service'

  - job_name: 'user-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'user-service:8087' ]
        labels:
          application: 'user-service'

  - job_name: 'payment-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'payment-service:8088' ]
        labels:
          application: 'payment-service'

  - job_name: 'web-storefront'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['web-storefront:8090']
        labels:
          application: 'web-storefront'

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']