spring:
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: ${AUTH_SERVICE_URL:http://localhost:8081}
          predicates: [Path=/api/v1/auth/**]
        - id: user-service
          uri: ${USER_SERVICE_URL:http://localhost:8087}
          predicates: [Path=/api/v1/users/**]
          filters:
            - name: RequestRateLimiter
              args:
                key-resolver: "#{@userKeyResolver}"
                redis-rate-limiter.replenishRate: 20
                redis-rate-limiter.burstCapacity: 40
        - id: catalog-service
          uri: ${CATALOG_SERVICE_URL:http://localhost:8082}
          predicates: [Path=/api/v1/products/**]
          filters:
            - name: RequestRateLimiter
              args:
                key-resolver: "#{@userKeyResolver}"
                redis-rate-limiter.replenishRate: 20
                redis-rate-limiter.burstCapacity: 40
        - id: inventory-service
          uri: ${INVENTORY_SERVICE_URL:http://localhost:8086}
          predicates: [Path=/api/v1/inventory/**]
          filters:
            - name: RequestRateLimiter
              args:
                key-resolver: "#{@userKeyResolver}"
                redis-rate-limiter.replenishRate: 20
                redis-rate-limiter.burstCapacity: 40
        - id: order-service
          uri: ${ORDER_SERVICE_URL:http://localhost:8083}
          predicates: ["Path=/api/v1/cart/**,/api/v1/orders/**"]
          filters:
            - name: RequestRateLimiter
              args:
                key-resolver: "#{@userKeyResolver}"
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
        - id: payment-service
          uri: ${PAYMENT_SERVICE_URL:http://localhost:8088}
          predicates: [Path=/api/v1/payments/**]
          filters:
            - name: RequestRateLimiter
              args:
                key-resolver: "#{@userKeyResolver}"
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
        - id: notification-service
          uri: ${NOTIFICATION_SERVICE_URL:http://localhost:8084}
          predicates: [Path=/api/v1/notifications/**]
  data:
    redis:
      host: ${SPRING_REDIS_HOST:localhost}
      port: ${SPRING_REDIS_PORT:6379}
